name: Deploy to Tomcat in Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy to Tomcat in Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.172.19.1.220 }}
          username: ${{ secrets.root }}
          password: ${{ secrets.vagrant }}
          script: |
            docker cp target/webapp.war tom1:/usr/local/tomcat/webapps/ROOT.war
