name: Deploy to Tomcat

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy to Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.172.19.1.220:8086}}
          username: ${{ secrets.admin }}
          password: ${{ secrets.admin }}
          script: |
            cd /usr/local/tomcat/webapps
            rm -rf ROOT
            cp /path/to/your/war/file ROOT.war
            sudo systemctl restart tomcat
